### ISSUE TITLE
max_input_vars for fftcgdb.com set too low to support Collection

### ISSUE THREAD

**Issue by nfraker** [danives/FFTCGDB#1]
I noticed when managing my collection on fftcgdb.com that it would not permit me to update my collection once the number of cards reached a certain point. I rebuilt the site in a docker container for troubleshooting and found this error in the Apache logs:

`[Thu Jul 20 18:30:12.960121 2017] [:error] [pid 513] [client 192.168.59.3:49169] PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0, referer: http://192.168.59.105/collection`

So the cause of the collection issue seems to be that there are too many values being posted to PHP through the interface, and it's dropping the request as a result. The solution is to increase max_input_vars in php.ini from the default 1000 to something more ridiculous (i went with 65534 for fun). I've verified this in my own containerized version of fftcgdb.com (https://github.com/nfraker/FFTCGDB/blob/FEATURE-add-dockerfile/Dockerfile#L59) and can now maintain my full collection without issues.

**Comment by HandsomeStrife** [comment]
Have updated the php.ini file as per request :)
