### ISSUE TITLE
Messages Is Busted

### ISSUE THREAD

**Issue by nfraker** [danives/FFTCGDB#12]
Hey @danives, I think if someone sends you a message on FFTCGDB.com it may be resulting in a 500 error now? I tried to send you a message on my account and I get a 500 error when I load the page, so I made a new account and tried to send you a message on that account, and now I get a 500 error when I load messages on there, too.

I can start trying to reproduce this, but I imagine it's going to be something that requires a copy of the prod db to diagnose (I'm currently tracking three bugs that i have narrowed down to either the controllers being different in prod than in the repo, or problems with the content of the current state of the prod DB).

**Comment by HandsomeStrife** [comment]
Yeah I'm not sure what started causing that - I got some error messages come through into my email and decided to check it out. While I don't know what has suddenly caused it, its basically trying to find "non-deleted" messages.

There might be a better way to track errors, perhaps storing them in the database so they can be viewed in an admin console. Currently I'm just emailed the error output (https://github.com/danives/FFTCGDB/blob/master/app/Exceptions/Handler.php#L50 and https://github.com/danives/FFTCGDB/blob/master/app/Mail/Error.php) which is fine, although recently I've been receiving a *lot* of database connection errors. I'm not exactly sure as to why but if it keeps happening I'll migrate them over.

I'm also meaning to abstract the cards into a JSON format so they can easily be updated and versioned via GitHub, which will also then allow for easier multilingual implementation.
